spring:
    datasource:
#        url: jdbc:mysql://localhost:3308/board?useSSL=false&serverTimezone=Asia/Seoul
#        username: root
#        password: 1234
        url: jdbc:mysql://awseb-e-dbre3ddjbm-stack-awsebrdsdatabase-f24h2tcdrapl.cx0htjilzftq.ap-northeast-2.rds.amazonaws.com/board?useSSL=false&serverTimezone=Asia/Seoul
        username: fastcam
        password: votmxmzoa0918
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

